### ISSUE TITLE
Enable clippy during tests

### ISSUE THREAD

**Issue by aaronmondal** [allada/turbo-cache#153]
A draft of this is at #152.

My current migration plan:

- [x] #158  Change impls of `Into` to `From` since the latter gives the former for free
- [x] #163 Implement `is_empty` for `LenEntry` and all its impls

Add remaining fixes separately:

- [x] #170 `cas/grpc_service`
- [x] #181 `cas/scheduler`
- [x] #171 `cas/store`
- [x] #169 `cas/worker`
- [x] #172 The remaining files

Finally:

- [x] #182

Additional issues/questions I encountered so far:

- [x] Clippy doesn't like the `highest_priority_action_first` and `equal_priority_earliest_first` tests in `cas/scheduler/tests/action_messages_test.rs`. I'm not sure what these tests are trying to test. Is this about `Ord`? Would testing something like `assert!(first_action < current_action)` or similar also work?
- [x] #174 The `GetFinishedResult` in `cas/worker/tests/utils/mock_running_actions_manager.rs` pointed out that the largest `GetFinishedResult` variant contains at least 496 bytes. It's talking about `ActionResult` here. I'd expect this to be fairly large but should it really be *this* large at all times?
- [x] We "hold a `RefCell` reference across an await point" in `cas/store/tests/filesystem_store_test.rs` L731. Seems like something is wrong there.

**Comment by allada** [comment]
Try and hold off on the scheduler stuff until @chrisstaite-menlo has landed his changes.

**Comment by allada** [comment]
> We "hold a RefCell reference across an await point" in cas/store/tests/filesystem_store_test.rs L731. Seems like something is wrong there.

I ended up disabling this warning. I tried to turn it into a mutex but it didn't help, it just gave another clippy error. In this case the reason it's complaining is because we "might" deadlock because we are calling an async function while we hold a lock (for mutex). The `RefCell` is complaining because technically multiple people can mutate the object in random places in the code without a clear code path of where all has mutable references. Granted this would all happen on the same thread (because `Rc` is not `Send`). All it's trying to do is make sure that the promise is still pending and the way it does this is by wrapping the future in another future temporary and calling pretty much calling await on it... This allows the outer future to get a context and then it calls `.poll()` on the inner future, and returns the `Polling` results. In this case it's a test and I don't see a direct way to fix this without turning off the warning.

**Comment by allada** [comment]
> The GetFinishedResult in cas/worker/tests/utils/mock_running_actions_manager.rs pointed out that the largest GetFinishedResult variant contains at least 496 bytes. It's talking about ActionResult here. I'd expect this to be fairly large but should it really be this large at all times?

Hmmm, I can do some simple math on this:
* 9 * sizeof(SystemTime)
* 4 * sizeof(Vec<_>)
* 2 * sizeof(DigestInfo)
* 1 * i32
* 1 * sizeof(HashMap<_, _>)
* 1 * sizeof(String)
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=29c3e096a14d764a417e3197f19c6801

Sums to 460, so yeah, my math is probably off a little because of `DigestInfo`'s `LazyTransform`.

**Comment by allada** [comment]
FYI https://github.com/allada/turbo-cache/pull/174 almost certainly is going to trigger many places where we call `.clone()` but it's trivial copyable now, so we'll need to re-run clippy on many directories that were already fixed.

**Comment by aaronmondal** [comment]
Closed by #182 Onwards to pedantic :rofl: :tada: :partying_face: :balloon: :cake:
